import { AutoTokenizer } from '../src/transformers.js';
import { getFile } from '../src/utils/hub.js';
import { isDeepEqual } from './test_utils.js';

(async () => {
    // Load test data generated by the python tests
    let testsData = await (await getFile('./tests/tokenizers/tests.json')).json()

    for (let [tokenizerName, tests] of Object.entries(testsData)) {
        let tokenizer = await AutoTokenizer.from_pretrained(tokenizerName);
        for (let test of tests) {
            let encoded = await tokenizer(test.input, {
                return_tensor: false
            });

            if (isDeepEqual(encoded, test.target)) {
                continue;
            }

            // Log if the test fails
            console.log({
                name: tokenizerName,
                text: test.input,
                output: encoded,
                target: test.target,
            })
        }
    }
})();

