const { AutoTokenizer } = require('..');
const { getFile } = require('../src/utils.js');
const path = require('path');
const { isDeepEqual } = require('./test_utils.js');

const BASE_DIR = './models/';

(async () => {
    // Load test data generated by the python tests
    let testsData = await (await getFile('./tests/tokenizers/tests.json')).json()

    for (let [tokenizerName, tests] of Object.entries(testsData)) {
        let tokenizer = await AutoTokenizer.from_pretrained(
            path.join(BASE_DIR, tokenizerName)
        );
        for (let test of tests) {
            let encoded = await tokenizer(test.input, {
                return_tensor: false
            });
            let matches = isDeepEqual(encoded, test.target);
            console.log({
                output: encoded,
                target: test.target,
                matches
            })
        }
    }
})();

